version: '3.3'

services:
  app:
    image: bb-registration-api-image
    ports:
      - 3355:3003
    networks:
      - web
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./mockoon-registration.json:/mockoon-registration.json

networks:
  web:
    driver: bridge
